services:
  pingora-proxy:
    image: dduldduck/pingora-proxy-manager:latest
    container_name: pingora-proxy
    restart: always
    ports:
      - "80:8080"   # HTTP Proxy (Backend listens on 8080)
      - "81:81"     # Dashboard/API (Backend listens on 81)
      - "443:443" 
    volumes:
      - ./data:/app/data        # DB and Certs persistence
      - ./logs:/app/logs        # Logs persistence
    environment:
      - JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      - RUST_LOG=info
